#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""B7 — 重生成 domain_map.ps1（唯一权威 domainMap）。

背景：现文件是 2026-08-08 auto-fix.ps1 生成的 160 条旧快照（含大量已退役 skill），
与 skill_content 的 151 条不符 → degradation-test 3a / 3d FAIL → content_snr M4 判「金标准陈旧」。

生成口径与 auto-fix.ps1 的 Fix-DomainMapCount 完全一致（仅多排除 index_manifest.json）：
  · 域 = skill_content 下 *.json 的 BaseName，排除 skill_ids.json / index_manifest.json / *.bak
  · 每域 skill 名 = 该 JSON 的 skills[].name（排序）
安全：写前打印差异 + 写后复读核对；备份落受管根外。
"""
import datetime
import json
import os
import shutil
import sys

SC = r"D:\global_memory\skill_content"
DM = r"D:\global_memory\scripts\domain_map.ps1"
BAK = r"D:\global_memory_archive\_trash\registry-normalize-20260922"

HEAD = """# domain_map.ps1 -- single-authority domain mapping table (auto-regenerated from JSON registry)
# ==========================================================
# NOTE: This is the SINGLE authoritative source for domainMap.
# Auto-regenerated by auto-fix.ps1 on {ts}
# 2026-09-22 第 10 轮：由 05-exec/B7-regen-domain-map.py 重生成（排除 index_manifest.json）
# ==========================================================
$domainMap = @{{
"""

TAIL = """}

function Get-DomainMapStats {
    $total = 0
    $stats = @{}
    foreach ($key in $domainMap.Keys) {
        $count = $domainMap[$key].Count
        $stats[$key] = $count
        $total += $count
    }
    return @{ stats = $stats; total = $total }
}
"""


def main():
    dry = "--dry-run" in sys.argv[1:]
    counts = {}
    for fn in sorted(os.listdir(SC)):
        if not fn.endswith(".json") or fn in ("skill_ids.json", "index_manifest.json") or fn.endswith(".bak"):
            continue
        with open(os.path.join(SC, fn), encoding="utf-8") as f:
            data = json.load(f)
        names = sorted(s.get("name") for s in (data.get("skills") or []))
        counts[fn[:-5]] = names

    total = sum(len(v) for v in counts.values())
    lines = []
    for dom in sorted(counts):
        names = counts[dom]
        if not names:
            print(f"[FAIL] 域 {dom} 为空，拒绝生成（会造成 3b 空域假 FAIL）")
            return 1
        joined = "'" + "', '".join(names) + "'"
        lines.append(f"    {dom} = @({joined})")

    new = HEAD.format(ts=datetime.datetime.now().strftime("%Y-%m-%d %H:%M")) \
        + "\n".join(lines) + "\n" + TAIL

    old = open(DM, encoding="utf-8").read() if os.path.exists(DM) else ""
    print(f"[plan] 域数 {len(counts)} / skill 总数 {total}")
    print(f"[plan] 旧文件 {len(old)}B → 新文件 {len(new)}B；内容{'不同' if old != new else '相同'}")

    if dry:
        print("[dry-run] 未写盘")
        return 0
    if old == new:
        print("[no-op] 已是最新")
        return 0

    os.makedirs(BAK, exist_ok=True)
    shutil.copy2(DM, os.path.join(BAK, "domain_map.ps1.bak"))
    with open(DM, "w", encoding="utf-8", newline="\n") as f:
        f.write(new)

    # 写后复读核对
    back = open(DM, encoding="utf-8").read()
    if back != new:
        print("[FAIL] 写后不一致")
        return 1
    print(f"[WRITE] {DM} 复验 OK（{total} 条 / {len(counts)} 域）")
    return 0


if __name__ == "__main__":
    sys.exit(main())
